### PR TITLE
Implement python tracebacks

### PR DESCRIPTION
**Pull request by Mdrbhatti**
Implements the python Traceback module as defined here: 
https://docs.python.org/2/library/traceback.html

### CODE REVIEW

**Comment by Mdrbhatti** [comment]
The only current issue I am facing in all of this right now is getting this test to pass:
https://github.com/Mdrbhatti/Ninia/blob/master/pytests/threads/tracebackTest.py#L63

The last string in the whole list is being printed as: 
[..... 'IndexError: tuple index out of range\n']

whereas cpython prints it as:
[..... "IndexError: tuple index out of range\n"]

Not too sure as to what I should do to change the single quotes to double quotes so that it matches cpython output. This issue arises only in the last string of the list, otherwise all the other strings start and end with a single quote. (If it weren't for this pesky last string, the test would pass!)

Ninia function implementation is here (line for the relevant last string is marked):
https://github.com/Mdrbhatti/Ninia/blob/master/src/traceback.ts#L188

**Comment by jvilk** [comment]
You know... the entire traceback module in Python is [written in Python](https://github.com/python/cpython/blob/2.7/Lib/traceback.py). I could merge this, but it will eventually be completely removed in favor of putting as much logic into Python code as possible. At the moment, Ninia cannot load `traceback` due to our types not being completely compatible (it chokes in importing `types`).

I'm sorry that we didn't discuss this ahead of time. I never checked to see how tracebacks were implemented. I am willing to merge it as-is, but it will be removed once we can load that module.

Is that OK with you?

**Comment by Mdrbhatti** [comment]
It's OK with me.

**Comment by jvilk** [comment]
Alrighty, this looks good to me!

**Pull request merged**
